FROM jupyter/scipy-notebook:65761486d5d3

USER root
RUN apt-get update
RUN apt-get install -y python3-dev libpq-dev
RUN apt install -y chromium-browser \
  && apt-get install chromium-chromedriver

# Install
RUN pip install --upgrade pip \
  && pip install -U janome  \
  && pip install -U gensim \
  && pip install -U networkx \
  && pip install -U joblib \
  && pip install -U selenium \
  && pip install -U requests

CMD jupyter notebook --allow-root --NotebookApp.token="$NOTEBOOK_PASSWORD" /opt/analysis
