version: '3'
services:
  jupyter:
    env_file: ./.env
    build:
      context: .
      dockerfile: ./Dockerfile-jupyter
    restart: always
    volumes:
      - "${SCRIPTS_SRC}:/opt/analysis"
    ports:
      - "8888:8888"
  web:
    build:
      context: .
      dockerfile: ./Dockerfile-flask
    tty: true
    volumes:
      - ./WebApp:/WebApp
    ports:
      - "5000:5000"

