version: '3'
services:
 jupyter:
    env_file: ./.env
    build:
      context: .
      dockerfile: ./Dockerfile-jupyter
    restart: always
    volumes:
      - "${SCRIPTS_SRC}:/opt/analysis"
    ports:
      - "8888:8888"

